module.exports = Object.freeze({
  version: 1,
  name: "skinalpha_priority_coverage_set",
  description:
    "Top market-significance watchlist for SkinAlpha priority coverage and scanner focus",
  tiers: Object.freeze({
    tier_a: Object.freeze({
      description:
        "Highest-priority items for strongest freshness, coverage, snapshots, and scan budget",
      policy_hints: Object.freeze({
        snapshot_priority: "highest",
        scan_budget: "highest",
        freshness_target: "strongest",
        coverage_target: "strongest",
        recovery_weight: 1
      }),
      items: Object.freeze([
        { category: "skin", item_name: "AWP | Dragon Lore" },
        { category: "skin", item_name: "AWP | Gungnir" },
        { category: "skin", item_name: "AK-47 | Wild Lotus" },
        { category: "skin", item_name: "AK-47 | Fire Serpent" },
        { category: "skin", item_name: "AK-47 | Gold Arabesque" },
        { category: "skin", item_name: "M4A4 | Howl" },
        { category: "skin", item_name: "M4A1-S | Welcome to the Jungle" },
        { category: "skin", item_name: "M4A1-S | Blue Phosphor" },
        { category: "skin", item_name: "Desert Eagle | Blaze" },
        { category: "skin", item_name: "Glock-18 | Fade" },
        { category: "case", item_name: "CS:GO Weapon Case" },
        { category: "case", item_name: "Operation Bravo Case" },
        { category: "case", item_name: "Operation Hydra Case" },
        { category: "case", item_name: "Winter Offensive Weapon Case" },
        { category: "case", item_name: "Glove Case" },
        { category: "case", item_name: "Shattered Web Case" },
        { category: "knife", item_name: "Karambit | Case Hardened" },
        { category: "knife", item_name: "Karambit | Doppler Sapphire" },
        { category: "knife", item_name: "Karambit | Gamma Doppler Emerald" },
        { category: "knife", item_name: "Butterfly Knife | Doppler Sapphire" },
        { category: "knife", item_name: "Butterfly Knife | Gamma Doppler Emerald" },
        { category: "knife", item_name: "M9 Bayonet | Gamma Doppler Emerald" },
        { category: "knife", item_name: "M9 Bayonet | Doppler Ruby" },
        { category: "knife", item_name: "M9 Bayonet | Fade" },
        { category: "glove", item_name: "Sport Gloves | Pandora's Box" },
        { category: "glove", item_name: "Sport Gloves | Hedge Maze" },
        { category: "glove", item_name: "Sport Gloves | Vice" },
        { category: "glove", item_name: "Sport Gloves | Superconductor" },
        { category: "glove", item_name: "Specialist Gloves | Crimson Kimono" },
        { category: "glove", item_name: "Driver Gloves | King Snake" }
      ])
    }),
    tier_b: Object.freeze({
      description: "Extended hot-universe items for broader scanner focus",
      policy_hints: Object.freeze({
        snapshot_priority: "high",
        scan_budget: "medium",
        freshness_target: "normal",
        coverage_target: "normal",
        recovery_weight: 0.7
      }),
      items: Object.freeze([
        { category: "skin", item_name: "AWP | Medusa" },
        { category: "skin", item_name: "AWP | Asiimov" },
        { category: "skin", item_name: "AWP | Lightning Strike" },
        { category: "skin", item_name: "AK-47 | Case Hardened" },
        { category: "skin", item_name: "AK-47 | Vulcan" },
        { category: "skin", item_name: "AK-47 | Redline" },
        { category: "skin", item_name: "AK-47 | Hydroponic" },
        { category: "skin", item_name: "AK-47 | Panthera onca" },
        { category: "skin", item_name: "AK-47 | Jet Set" },
        { category: "skin", item_name: "M4A4 | Poseidon" },
        { category: "skin", item_name: "M4A4 | Eye of Horus" },
        { category: "skin", item_name: "M4A4 | Asiimov" },
        { category: "skin", item_name: "M4A4 | The Emperor" },
        { category: "skin", item_name: "M4A4 | Neo-Noir" },
        { category: "skin", item_name: "M4A4 | Hellfire" },
        { category: "skin", item_name: "M4A4 | Desolate Space" },
        { category: "skin", item_name: "M4A1-S | Knight" },
        { category: "skin", item_name: "M4A1-S | Printstream" },
        { category: "skin", item_name: "M4A1-S | Hot Rod" },
        { category: "skin", item_name: "M4A1-S | Vaporwave" },
        { category: "skin", item_name: "M4A1-S | Golden Coil" },
        { category: "skin", item_name: "USP-S | Kill Confirmed" },
        { category: "skin", item_name: "USP-S | Printstream" },
        { category: "skin", item_name: "USP-S | Orion" },
        { category: "skin", item_name: "USP-S | Neo-Noir" },
        { category: "skin", item_name: "Desert Eagle | Printstream" },
        { category: "skin", item_name: "Desert Eagle | Fennec Fox" },
        { category: "skin", item_name: "Desert Eagle | Emerald Jörmungandr" },
        { category: "skin", item_name: "Glock-18 | Gamma Doppler" },
        { category: "skin", item_name: "FAMAS | Commemoration" },
        { category: "case", item_name: "Operation Phoenix Weapon Case" },
        { category: "case", item_name: "Huntsman Weapon Case" },
        { category: "case", item_name: "Operation Wildfire Case" },
        { category: "case", item_name: "Shadow Case" },
        { category: "case", item_name: "Chroma Case" },
        { category: "case", item_name: "Chroma 2 Case" },
        { category: "case", item_name: "Chroma 3 Case" },
        { category: "case", item_name: "Gamma Case" },
        { category: "case", item_name: "Gamma 2 Case" },
        { category: "case", item_name: "Prisma 2 Case" },
        { category: "case", item_name: "Dreams & Nightmares Case" },
        { category: "case", item_name: "Revolution Case" },
        { category: "case", item_name: "Kilowatt Case" },
        { category: "case", item_name: "Gallery Case" },
        { category: "knife", item_name: "Karambit | Fade" },
        { category: "knife", item_name: "Butterfly Knife | Fade" },
        { category: "knife", item_name: "Butterfly Knife | Lore" },
        { category: "knife", item_name: "Butterfly Knife | Slaughter" },
        { category: "knife", item_name: "M9 Bayonet | Crimson Web" },
        { category: "knife", item_name: "M9 Bayonet | Lore" },
        { category: "knife", item_name: "M9 Bayonet | Case Hardened" },
        { category: "knife", item_name: "Bayonet | Doppler Sapphire" },
        { category: "knife", item_name: "Bayonet | Gamma Doppler Emerald" },
        { category: "knife", item_name: "Bayonet | Fade" },
        { category: "knife", item_name: "Skeleton Knife | Crimson Web" },
        { category: "knife", item_name: "Flip Knife | Gamma Doppler" },
        { category: "glove", item_name: "Sport Gloves | Amphibious" },
        { category: "glove", item_name: "Sport Gloves | Omega" },
        { category: "glove", item_name: "Sport Gloves | Nocts" },
        { category: "glove", item_name: "Sport Gloves | Slingshot" },
        { category: "glove", item_name: "Specialist Gloves | Fade" },
        { category: "glove", item_name: "Specialist Gloves | Marble Fade" },
        { category: "glove", item_name: "Specialist Gloves | Emerald Web" },
        { category: "glove", item_name: "Specialist Gloves | Foundation" },
        { category: "glove", item_name: "Specialist Gloves | Mogul" },
        { category: "glove", item_name: "Driver Gloves | Imperial Plaid" },
        { category: "glove", item_name: "Driver Gloves | Snow Leopard" },
        { category: "glove", item_name: "Driver Gloves | Black Tie" },
        { category: "glove", item_name: "Moto Gloves | Spearmint" },
        { category: "glove", item_name: "Hand Wraps | Cobalt Skulls" }
      ])
    })
  })
})
