const MANUAL_PRIMARY_CATEGORY_COUNTS = Object.freeze({
  weapon_skin: 380,
  case: 70,
  sticker_capsule: 50,
  total: 500
})

const WEAPON_SKIN_ITEMS = Object.freeze([
  "AK-47 | Asiimov (Minimal Wear)",
  "AK-47 | Asiimov (Field-Tested)",
  "AK-47 | Asiimov (Well-Worn)",
  "AK-47 | Asiimov (Battle-Scarred)",
  "StatTrak\u2122 AK-47 | Asiimov (Field-Tested)",
  "AK-47 | Aquamarine Revenge (Minimal Wear)",
  "AK-47 | Aquamarine Revenge (Field-Tested)",
  "AK-47 | Aquamarine Revenge (Well-Worn)",
  "AK-47 | Aquamarine Revenge (Battle-Scarred)",
  "StatTrak\u2122 AK-47 | Aquamarine Revenge (Field-Tested)",
  "AK-47 | Bloodsport (Minimal Wear)",
  "AK-47 | Bloodsport (Field-Tested)",
  "AK-47 | Bloodsport (Well-Worn)",
  "AK-47 | Bloodsport (Battle-Scarred)",
  "StatTrak\u2122 AK-47 | Bloodsport (Field-Tested)",
  "AK-47 | Case Hardened (Minimal Wear)",
  "AK-47 | Case Hardened (Field-Tested)",
  "AK-47 | Case Hardened (Well-Worn)",
  "AK-47 | Case Hardened (Battle-Scarred)",
  "StatTrak\u2122 AK-47 | Case Hardened (Field-Tested)",
  "AK-47 | Frontside Misty (Minimal Wear)",
  "AK-47 | Frontside Misty (Field-Tested)",
  "AK-47 | Frontside Misty (Well-Worn)",
  "AK-47 | Frontside Misty (Battle-Scarred)",
  "StatTrak\u2122 AK-47 | Frontside Misty (Field-Tested)",
  "AK-47 | Head Shot (Minimal Wear)",
  "AK-47 | Head Shot (Field-Tested)",
  "AK-47 | Head Shot (Well-Worn)",
  "AK-47 | Head Shot (Battle-Scarred)",
  "StatTrak\u2122 AK-47 | Head Shot (Field-Tested)",
  "AK-47 | Ice Coaled (Minimal Wear)",
  "AK-47 | Ice Coaled (Field-Tested)",
  "AK-47 | Ice Coaled (Well-Worn)",
  "AK-47 | Ice Coaled (Battle-Scarred)",
  "StatTrak\u2122 AK-47 | Ice Coaled (Field-Tested)",
  "AK-47 | Legion of Anubis (Minimal Wear)",
  "AK-47 | Legion of Anubis (Field-Tested)",
  "AK-47 | Legion of Anubis (Well-Worn)",
  "AK-47 | Legion of Anubis (Battle-Scarred)",
  "StatTrak\u2122 AK-47 | Legion of Anubis (Field-Tested)",
  "AK-47 | Neon Revolution (Minimal Wear)",
  "AK-47 | Neon Revolution (Field-Tested)",
  "AK-47 | Neon Revolution (Well-Worn)",
  "AK-47 | Neon Revolution (Battle-Scarred)",
  "StatTrak\u2122 AK-47 | Neon Revolution (Field-Tested)",
  "AK-47 | Neon Rider (Minimal Wear)",
  "AK-47 | Neon Rider (Field-Tested)",
  "AK-47 | Neon Rider (Well-Worn)",
  "AK-47 | Neon Rider (Battle-Scarred)",
  "StatTrak\u2122 AK-47 | Neon Rider (Field-Tested)",
  "AK-47 | Phantom Disruptor (Minimal Wear)",
  "AK-47 | Phantom Disruptor (Field-Tested)",
  "AK-47 | Phantom Disruptor (Well-Worn)",
  "AK-47 | Phantom Disruptor (Battle-Scarred)",
  "StatTrak\u2122 AK-47 | Phantom Disruptor (Field-Tested)",
  "AK-47 | Point Disarray (Minimal Wear)",
  "AK-47 | Point Disarray (Field-Tested)",
  "AK-47 | Point Disarray (Well-Worn)",
  "AK-47 | Point Disarray (Battle-Scarred)",
  "StatTrak\u2122 AK-47 | Point Disarray (Field-Tested)",
  "AK-47 | Rat Rod (Minimal Wear)",
  "AK-47 | Rat Rod (Field-Tested)",
  "AK-47 | Rat Rod (Well-Worn)",
  "AK-47 | Rat Rod (Battle-Scarred)",
  "StatTrak\u2122 AK-47 | Rat Rod (Field-Tested)",
  "AK-47 | Redline (Minimal Wear)",
  "AK-47 | Redline (Field-Tested)",
  "AK-47 | Redline (Well-Worn)",
  "AK-47 | Redline (Battle-Scarred)",
  "StatTrak\u2122 AK-47 | Redline (Field-Tested)",
  "AK-47 | Slate (Minimal Wear)",
  "AK-47 | Slate (Field-Tested)",
  "AK-47 | Slate (Well-Worn)",
  "AK-47 | Slate (Battle-Scarred)",
  "StatTrak\u2122 AK-47 | Slate (Field-Tested)",
  "AK-47 | The Empress (Minimal Wear)",
  "AK-47 | The Empress (Field-Tested)",
  "AK-47 | The Empress (Well-Worn)",
  "AK-47 | The Empress (Battle-Scarred)",
  "StatTrak\u2122 AK-47 | The Empress (Field-Tested)",
  "AK-47 | Vulcan (Minimal Wear)",
  "AK-47 | Vulcan (Field-Tested)",
  "AK-47 | Vulcan (Well-Worn)",
  "AK-47 | Vulcan (Battle-Scarred)",
  "StatTrak\u2122 AK-47 | Vulcan (Field-Tested)",
  "AK-47 | Wasteland Rebel (Minimal Wear)",
  "AK-47 | Wasteland Rebel (Field-Tested)",
  "AK-47 | Wasteland Rebel (Well-Worn)",
  "AK-47 | Wasteland Rebel (Battle-Scarred)",
  "StatTrak\u2122 AK-47 | Wasteland Rebel (Field-Tested)",
  "AWP | Asiimov (Minimal Wear)",
  "AWP | Asiimov (Field-Tested)",
  "AWP | Asiimov (Well-Worn)",
  "AWP | Asiimov (Battle-Scarred)",
  "StatTrak\u2122 AWP | Asiimov (Field-Tested)",
  "AWP | Atheris (Minimal Wear)",
  "AWP | Atheris (Field-Tested)",
  "AWP | Atheris (Well-Worn)",
  "AWP | Atheris (Battle-Scarred)",
  "StatTrak\u2122 AWP | Atheris (Field-Tested)",
  "AWP | Chromatic Aberration (Minimal Wear)",
  "AWP | Chromatic Aberration (Field-Tested)",
  "AWP | Chromatic Aberration (Well-Worn)",
  "AWP | Chromatic Aberration (Battle-Scarred)",
  "StatTrak\u2122 AWP | Chromatic Aberration (Field-Tested)",
  "AWP | Containment Breach (Minimal Wear)",
  "AWP | Containment Breach (Field-Tested)",
  "AWP | Containment Breach (Well-Worn)",
  "AWP | Containment Breach (Battle-Scarred)",
  "StatTrak\u2122 AWP | Containment Breach (Field-Tested)",
  "AWP | Duality (Minimal Wear)",
  "AWP | Duality (Field-Tested)",
  "AWP | Duality (Well-Worn)",
  "AWP | Duality (Battle-Scarred)",
  "StatTrak\u2122 AWP | Duality (Field-Tested)",
  "AWP | Elite Build (Minimal Wear)",
  "AWP | Elite Build (Field-Tested)",
  "AWP | Elite Build (Well-Worn)",
  "AWP | Elite Build (Battle-Scarred)",
  "StatTrak\u2122 AWP | Elite Build (Field-Tested)",
  "AWP | Exoskeleton (Minimal Wear)",
  "AWP | Exoskeleton (Field-Tested)",
  "AWP | Exoskeleton (Well-Worn)",
  "AWP | Exoskeleton (Battle-Scarred)",
  "StatTrak\u2122 AWP | Exoskeleton (Field-Tested)",
  "AWP | Fever Dream (Minimal Wear)",
  "AWP | Fever Dream (Field-Tested)",
  "AWP | Fever Dream (Well-Worn)",
  "AWP | Fever Dream (Battle-Scarred)",
  "StatTrak\u2122 AWP | Fever Dream (Field-Tested)",
  "AWP | Hyper Beast (Minimal Wear)",
  "AWP | Hyper Beast (Field-Tested)",
  "AWP | Hyper Beast (Well-Worn)",
  "AWP | Hyper Beast (Battle-Scarred)",
  "StatTrak\u2122 AWP | Hyper Beast (Field-Tested)",
  "AWP | Man-o'war (Minimal Wear)",
  "AWP | Man-o'war (Field-Tested)",
  "AWP | Man-o'war (Well-Worn)",
  "AWP | Man-o'war (Battle-Scarred)",
  "StatTrak\u2122 AWP | Man-o'war (Field-Tested)",
  "AWP | Mortis (Minimal Wear)",
  "AWP | Mortis (Field-Tested)",
  "AWP | Mortis (Well-Worn)",
  "AWP | Mortis (Battle-Scarred)",
  "StatTrak\u2122 AWP | Mortis (Field-Tested)",
  "AWP | Neo-Noir (Minimal Wear)",
  "AWP | Neo-Noir (Field-Tested)",
  "AWP | Neo-Noir (Well-Worn)",
  "AWP | Neo-Noir (Battle-Scarred)",
  "StatTrak\u2122 AWP | Neo-Noir (Field-Tested)",
  "AWP | Redline (Minimal Wear)",
  "AWP | Redline (Field-Tested)",
  "AWP | Redline (Well-Worn)",
  "AWP | Redline (Battle-Scarred)",
  "StatTrak\u2122 AWP | Redline (Field-Tested)",
  "AWP | Wildfire (Minimal Wear)",
  "AWP | Wildfire (Field-Tested)",
  "AWP | Wildfire (Well-Worn)",
  "AWP | Wildfire (Battle-Scarred)",
  "StatTrak\u2122 AWP | Wildfire (Field-Tested)",
  "AWP | Worm God (Minimal Wear)",
  "AWP | Worm God (Field-Tested)",
  "AWP | Worm God (Well-Worn)",
  "AWP | Worm God (Battle-Scarred)",
  "StatTrak\u2122 AWP | Worm God (Field-Tested)",
  "M4A1-S | Black Lotus (Minimal Wear)",
  "M4A1-S | Black Lotus (Field-Tested)",
  "M4A1-S | Black Lotus (Well-Worn)",
  "M4A1-S | Black Lotus (Battle-Scarred)",
  "StatTrak\u2122 M4A1-S | Black Lotus (Field-Tested)",
  "M4A1-S | Chantico's Fire (Minimal Wear)",
  "M4A1-S | Chantico's Fire (Field-Tested)",
  "M4A1-S | Chantico's Fire (Well-Worn)",
  "M4A1-S | Chantico's Fire (Battle-Scarred)",
  "StatTrak\u2122 M4A1-S | Chantico's Fire (Field-Tested)",
  "M4A1-S | Cyrex (Minimal Wear)",
  "M4A1-S | Cyrex (Field-Tested)",
  "M4A1-S | Cyrex (Well-Worn)",
  "M4A1-S | Cyrex (Battle-Scarred)",
  "StatTrak\u2122 M4A1-S | Cyrex (Field-Tested)",
  "M4A1-S | Decimator (Minimal Wear)",
  "M4A1-S | Decimator (Field-Tested)",
  "M4A1-S | Decimator (Well-Worn)",
  "M4A1-S | Decimator (Battle-Scarred)",
  "StatTrak\u2122 M4A1-S | Decimator (Field-Tested)",
  "M4A1-S | Hyper Beast (Minimal Wear)",
  "M4A1-S | Hyper Beast (Field-Tested)",
  "M4A1-S | Hyper Beast (Well-Worn)",
  "M4A1-S | Hyper Beast (Battle-Scarred)",
  "StatTrak\u2122 M4A1-S | Hyper Beast (Field-Tested)",
  "M4A1-S | Leaded Glass (Minimal Wear)",
  "M4A1-S | Leaded Glass (Field-Tested)",
  "M4A1-S | Leaded Glass (Well-Worn)",
  "M4A1-S | Leaded Glass (Battle-Scarred)",
  "StatTrak\u2122 M4A1-S | Leaded Glass (Field-Tested)",
  "M4A1-S | Mecha Industries (Minimal Wear)",
  "M4A1-S | Mecha Industries (Field-Tested)",
  "M4A1-S | Mecha Industries (Well-Worn)",
  "M4A1-S | Mecha Industries (Battle-Scarred)",
  "StatTrak\u2122 M4A1-S | Mecha Industries (Field-Tested)",
  "M4A1-S | Nightmare (Minimal Wear)",
  "M4A1-S | Nightmare (Field-Tested)",
  "M4A1-S | Nightmare (Well-Worn)",
  "M4A1-S | Nightmare (Battle-Scarred)",
  "StatTrak\u2122 M4A1-S | Nightmare (Field-Tested)",
  "M4A1-S | Player Two (Minimal Wear)",
  "M4A1-S | Player Two (Field-Tested)",
  "M4A1-S | Player Two (Well-Worn)",
  "M4A1-S | Player Two (Battle-Scarred)",
  "StatTrak\u2122 M4A1-S | Player Two (Field-Tested)",
  "M4A1-S | Printstream (Minimal Wear)",
  "M4A1-S | Printstream (Field-Tested)",
  "M4A1-S | Printstream (Well-Worn)",
  "M4A1-S | Printstream (Battle-Scarred)",
  "StatTrak\u2122 M4A1-S | Printstream (Field-Tested)",
  "M4A4 | \u9f8d\u738b (Dragon King) (Minimal Wear)",
  "M4A4 | \u9f8d\u738b (Dragon King) (Field-Tested)",
  "M4A4 | \u9f8d\u738b (Dragon King) (Well-Worn)",
  "M4A4 | \u9f8d\u738b (Dragon King) (Battle-Scarred)",
  "StatTrak\u2122 M4A4 | \u9f8d\u738b (Dragon King) (Field-Tested)",
  "M4A4 | Buzz Kill (Minimal Wear)",
  "M4A4 | Buzz Kill (Field-Tested)",
  "M4A4 | Buzz Kill (Well-Worn)",
  "M4A4 | Buzz Kill (Battle-Scarred)",
  "StatTrak\u2122 M4A4 | Buzz Kill (Field-Tested)",
  "M4A4 | Cyber Security (Minimal Wear)",
  "M4A4 | Cyber Security (Field-Tested)",
  "M4A4 | Cyber Security (Well-Worn)",
  "M4A4 | Cyber Security (Battle-Scarred)",
  "StatTrak\u2122 M4A4 | Cyber Security (Field-Tested)",
  "M4A4 | Desolate Space (Minimal Wear)",
  "M4A4 | Desolate Space (Field-Tested)",
  "M4A4 | Desolate Space (Well-Worn)",
  "M4A4 | Desolate Space (Battle-Scarred)",
  "StatTrak\u2122 M4A4 | Desolate Space (Field-Tested)",
  "M4A4 | Evil Daimyo (Minimal Wear)",
  "M4A4 | Evil Daimyo (Field-Tested)",
  "M4A4 | Evil Daimyo (Well-Worn)",
  "M4A4 | Evil Daimyo (Battle-Scarred)",
  "StatTrak\u2122 M4A4 | Evil Daimyo (Field-Tested)",
  "M4A4 | In Living Color (Minimal Wear)",
  "M4A4 | In Living Color (Field-Tested)",
  "M4A4 | In Living Color (Well-Worn)",
  "M4A4 | In Living Color (Battle-Scarred)",
  "StatTrak\u2122 M4A4 | In Living Color (Field-Tested)",
  "M4A4 | Neo-Noir (Minimal Wear)",
  "M4A4 | Neo-Noir (Field-Tested)",
  "M4A4 | Neo-Noir (Well-Worn)",
  "M4A4 | Neo-Noir (Battle-Scarred)",
  "StatTrak\u2122 M4A4 | Neo-Noir (Field-Tested)",
  "M4A4 | Temukau (Minimal Wear)",
  "M4A4 | Temukau (Field-Tested)",
  "M4A4 | Temukau (Well-Worn)",
  "M4A4 | Temukau (Battle-Scarred)",
  "StatTrak\u2122 M4A4 | Temukau (Field-Tested)",
  "M4A4 | The Emperor (Minimal Wear)",
  "M4A4 | The Emperor (Field-Tested)",
  "M4A4 | The Emperor (Well-Worn)",
  "M4A4 | The Emperor (Battle-Scarred)",
  "StatTrak\u2122 M4A4 | The Emperor (Field-Tested)",
  "M4A4 | Tooth Fairy (Minimal Wear)",
  "M4A4 | Tooth Fairy (Field-Tested)",
  "M4A4 | Tooth Fairy (Well-Worn)",
  "M4A4 | Tooth Fairy (Battle-Scarred)",
  "StatTrak\u2122 M4A4 | Tooth Fairy (Field-Tested)",
  "USP-S | Black Lotus (Minimal Wear)",
  "USP-S | Black Lotus (Field-Tested)",
  "USP-S | Black Lotus (Well-Worn)",
  "USP-S | Black Lotus (Battle-Scarred)",
  "StatTrak\u2122 USP-S | Black Lotus (Field-Tested)",
  "USP-S | Cortex (Minimal Wear)",
  "USP-S | Cortex (Field-Tested)",
  "USP-S | Cortex (Well-Worn)",
  "USP-S | Cortex (Battle-Scarred)",
  "StatTrak\u2122 USP-S | Cortex (Field-Tested)",
  "USP-S | Cyrex (Minimal Wear)",
  "USP-S | Cyrex (Field-Tested)",
  "USP-S | Cyrex (Well-Worn)",
  "USP-S | Cyrex (Battle-Scarred)",
  "StatTrak\u2122 USP-S | Cyrex (Field-Tested)",
  "USP-S | Jawbreaker (Minimal Wear)",
  "USP-S | Jawbreaker (Field-Tested)",
  "USP-S | Jawbreaker (Well-Worn)",
  "USP-S | Jawbreaker (Battle-Scarred)",
  "StatTrak\u2122 USP-S | Jawbreaker (Field-Tested)",
  "USP-S | Kill Confirmed (Minimal Wear)",
  "USP-S | Kill Confirmed (Field-Tested)",
  "USP-S | Kill Confirmed (Well-Worn)",
  "USP-S | Kill Confirmed (Battle-Scarred)",
  "StatTrak\u2122 USP-S | Kill Confirmed (Field-Tested)",
  "USP-S | Monster Mashup (Minimal Wear)",
  "USP-S | Monster Mashup (Field-Tested)",
  "USP-S | Monster Mashup (Well-Worn)",
  "USP-S | Monster Mashup (Battle-Scarred)",
  "StatTrak\u2122 USP-S | Monster Mashup (Field-Tested)",
  "USP-S | Neo-Noir (Minimal Wear)",
  "USP-S | Neo-Noir (Field-Tested)",
  "USP-S | Neo-Noir (Well-Worn)",
  "USP-S | Neo-Noir (Battle-Scarred)",
  "StatTrak\u2122 USP-S | Neo-Noir (Field-Tested)",
  "USP-S | Printstream (Minimal Wear)",
  "USP-S | Printstream (Field-Tested)",
  "USP-S | Printstream (Well-Worn)",
  "USP-S | Printstream (Battle-Scarred)",
  "StatTrak\u2122 USP-S | Printstream (Field-Tested)",
  "Glock-18 | Bullet Queen (Minimal Wear)",
  "Glock-18 | Bullet Queen (Field-Tested)",
  "Glock-18 | Bullet Queen (Well-Worn)",
  "Glock-18 | Bullet Queen (Battle-Scarred)",
  "StatTrak\u2122 Glock-18 | Bullet Queen (Field-Tested)",
  "Glock-18 | Gold Toof (Minimal Wear)",
  "Glock-18 | Gold Toof (Field-Tested)",
  "Glock-18 | Gold Toof (Well-Worn)",
  "Glock-18 | Gold Toof (Battle-Scarred)",
  "StatTrak\u2122 Glock-18 | Gold Toof (Field-Tested)",
  "Glock-18 | Neo-Noir (Minimal Wear)",
  "Glock-18 | Neo-Noir (Field-Tested)",
  "Glock-18 | Neo-Noir (Well-Worn)",
  "Glock-18 | Neo-Noir (Battle-Scarred)",
  "StatTrak\u2122 Glock-18 | Neo-Noir (Field-Tested)",
  "Glock-18 | Nuclear Garden (Minimal Wear)",
  "Glock-18 | Nuclear Garden (Field-Tested)",
  "Glock-18 | Nuclear Garden (Well-Worn)",
  "Glock-18 | Nuclear Garden (Battle-Scarred)",
  "StatTrak\u2122 Glock-18 | Nuclear Garden (Field-Tested)",
  "Glock-18 | Snack Attack (Minimal Wear)",
  "Glock-18 | Snack Attack (Field-Tested)",
  "Glock-18 | Snack Attack (Well-Worn)",
  "Glock-18 | Snack Attack (Battle-Scarred)",
  "StatTrak\u2122 Glock-18 | Snack Attack (Field-Tested)",
  "Glock-18 | Vogue (Minimal Wear)",
  "Glock-18 | Vogue (Field-Tested)",
  "Glock-18 | Vogue (Well-Worn)",
  "Glock-18 | Vogue (Battle-Scarred)",
  "StatTrak\u2122 Glock-18 | Vogue (Field-Tested)",
  "Glock-18 | Wasteland Rebel (Minimal Wear)",
  "Glock-18 | Wasteland Rebel (Field-Tested)",
  "Glock-18 | Wasteland Rebel (Well-Worn)",
  "Glock-18 | Wasteland Rebel (Battle-Scarred)",
  "StatTrak\u2122 Glock-18 | Wasteland Rebel (Field-Tested)",
  "Glock-18 | Water Elemental (Minimal Wear)",
  "Glock-18 | Water Elemental (Field-Tested)",
  "Glock-18 | Water Elemental (Well-Worn)",
  "Glock-18 | Water Elemental (Battle-Scarred)",
  "StatTrak\u2122 Glock-18 | Water Elemental (Field-Tested)",
  "Desert Eagle | Code Red (Minimal Wear)",
  "Desert Eagle | Code Red (Field-Tested)",
  "Desert Eagle | Code Red (Well-Worn)",
  "Desert Eagle | Code Red (Battle-Scarred)",
  "StatTrak\u2122 Desert Eagle | Code Red (Field-Tested)",
  "Desert Eagle | Crimson Web (Minimal Wear)",
  "Desert Eagle | Crimson Web (Field-Tested)",
  "Desert Eagle | Crimson Web (Well-Worn)",
  "Desert Eagle | Crimson Web (Battle-Scarred)",
  "StatTrak\u2122 Desert Eagle | Crimson Web (Field-Tested)",
  "Desert Eagle | Kumicho Dragon (Minimal Wear)",
  "Desert Eagle | Kumicho Dragon (Field-Tested)",
  "Desert Eagle | Kumicho Dragon (Well-Worn)",
  "Desert Eagle | Kumicho Dragon (Battle-Scarred)",
  "StatTrak\u2122 Desert Eagle | Kumicho Dragon (Field-Tested)",
  "Desert Eagle | Mecha Industries (Minimal Wear)",
  "Desert Eagle | Mecha Industries (Field-Tested)",
  "Desert Eagle | Mecha Industries (Well-Worn)",
  "Desert Eagle | Mecha Industries (Battle-Scarred)",
  "StatTrak\u2122 Desert Eagle | Mecha Industries (Field-Tested)",
  "Desert Eagle | Ocean Drive (Minimal Wear)",
  "Desert Eagle | Ocean Drive (Field-Tested)",
  "Desert Eagle | Ocean Drive (Well-Worn)",
  "Desert Eagle | Ocean Drive (Battle-Scarred)",
  "StatTrak\u2122 Desert Eagle | Ocean Drive (Field-Tested)",
  "Desert Eagle | Printstream (Minimal Wear)",
  "Desert Eagle | Printstream (Field-Tested)",
  "Desert Eagle | Printstream (Well-Worn)",
  "Desert Eagle | Printstream (Battle-Scarred)",
  "StatTrak\u2122 Desert Eagle | Printstream (Field-Tested)",
  "Desert Eagle | Trigger Discipline (Minimal Wear)",
  "Desert Eagle | Trigger Discipline (Field-Tested)",
  "Desert Eagle | Trigger Discipline (Well-Worn)",
  "Desert Eagle | Trigger Discipline (Battle-Scarred)",
  "StatTrak\u2122 Desert Eagle | Trigger Discipline (Field-Tested)"
])

const CASE_ITEMS = Object.freeze([
  "CS:GO Weapon Case",
  "eSports 2013 Case",
  "Operation Bravo Case",
  "CS:GO Weapon Case 2",
  "eSports 2013 Winter Case",
  "CS:GO Weapon Case 3",
  "Operation Phoenix Weapon Case",
  "Huntsman Weapon Case",
  "Operation Breakout Weapon Case",
  "eSports 2014 Summer Case",
  "Operation Vanguard Weapon Case",
  "Chroma Case",
  "Chroma 2 Case",
  "Falchion Case",
  "Shadow Case",
  "Revolver Case",
  "Operation Wildfire Case",
  "Chroma 3 Case",
  "Gamma Case",
  "Gamma 2 Case",
  "Glove Case",
  "Spectrum Case",
  "Operation Hydra Case",
  "Spectrum 2 Case",
  "Clutch Case",
  "Horizon Case",
  "Danger Zone Case",
  "Prisma Case",
  "CS20 Case",
  "Prisma 2 Case",
  "Shattered Web Case",
  "Fracture Case",
  "Operation Broken Fang Case",
  "Snakebite Case",
  "Operation Riptide Case",
  "Dreams & Nightmares Case",
  "Recoil Case",
  "Revolution Case",
  "Kilowatt Case",
  "Gallery Case",
  "Berlin 2019 Mirage Souvenir Package",
  "Berlin 2019 Dust II Souvenir Package",
  "Berlin 2019 Nuke Souvenir Package",
  "Berlin 2019 Inferno Souvenir Package",
  "Berlin 2019 Overpass Souvenir Package",
  "Stockholm 2021 Mirage Souvenir Package",
  "Stockholm 2021 Dust II Souvenir Package",
  "Stockholm 2021 Nuke Souvenir Package",
  "Stockholm 2021 Inferno Souvenir Package",
  "Stockholm 2021 Ancient Souvenir Package",
  "Antwerp 2022 Mirage Souvenir Package",
  "Antwerp 2022 Dust II Souvenir Package",
  "Antwerp 2022 Nuke Souvenir Package",
  "Antwerp 2022 Inferno Souvenir Package",
  "Antwerp 2022 Ancient Souvenir Package",
  "Rio 2022 Mirage Souvenir Package",
  "Rio 2022 Dust II Souvenir Package",
  "Rio 2022 Nuke Souvenir Package",
  "Rio 2022 Inferno Souvenir Package",
  "Rio 2022 Ancient Souvenir Package",
  "Paris 2023 Mirage Souvenir Package",
  "Paris 2023 Anubis Souvenir Package",
  "Paris 2023 Nuke Souvenir Package",
  "Paris 2023 Inferno Souvenir Package",
  "Paris 2023 Overpass Souvenir Package",
  "Copenhagen 2024 Mirage Souvenir Package",
  "Copenhagen 2024 Anubis Souvenir Package",
  "Copenhagen 2024 Nuke Souvenir Package",
  "Copenhagen 2024 Inferno Souvenir Package",
  "Copenhagen 2024 Ancient Souvenir Package"
])

const STICKER_CAPSULE_ITEMS = Object.freeze([
  "Stockholm 2021 Legends Sticker Capsule",
  "Stockholm 2021 Challengers Sticker Capsule",
  "Stockholm 2021 Contenders Sticker Capsule",
  "Stockholm 2021 Legends Autograph Capsule",
  "Stockholm 2021 Challengers Autograph Capsule",
  "Stockholm 2021 Contenders Autograph Capsule",
  "Antwerp 2022 Legends Sticker Capsule",
  "Antwerp 2022 Challengers Sticker Capsule",
  "Antwerp 2022 Contenders Sticker Capsule",
  "Antwerp 2022 Legends Autograph Capsule",
  "Antwerp 2022 Challengers Autograph Capsule",
  "Antwerp 2022 Contenders Autograph Capsule",
  "Rio 2022 Legends Sticker Capsule",
  "Rio 2022 Challengers Sticker Capsule",
  "Rio 2022 Contenders Sticker Capsule",
  "Rio 2022 Legends Autograph Capsule",
  "Rio 2022 Challengers Autograph Capsule",
  "Rio 2022 Contenders Autograph Capsule",
  "Paris 2023 Legends Sticker Capsule",
  "Paris 2023 Challengers Sticker Capsule",
  "Paris 2023 Contenders Sticker Capsule",
  "Paris 2023 Legends Autograph Capsule",
  "Paris 2023 Challengers Autograph Capsule",
  "Paris 2023 Contenders Autograph Capsule",
  "Copenhagen 2024 Legends Sticker Capsule",
  "Copenhagen 2024 Challengers Sticker Capsule",
  "Copenhagen 2024 Contenders Sticker Capsule",
  "Copenhagen 2024 Legends Autograph Capsule",
  "Copenhagen 2024 Challengers Autograph Capsule",
  "Copenhagen 2024 Contenders Autograph Capsule",
  "2020 RMR Legends Sticker Capsule",
  "2020 RMR Challengers Sticker Capsule",
  "2020 RMR Contenders Sticker Capsule",
  "2020 RMR Legends Autograph Capsule",
  "2020 RMR Challengers Autograph Capsule",
  "2020 RMR Contenders Autograph Capsule",
  "10 Year Birthday Sticker Capsule",
  "2021 Community Sticker Capsule",
  "Bestiary Capsule",
  "Community Sticker Capsule 1",
  "CS20 Sticker Capsule",
  "Enfu Sticker Capsule",
  "Feral Predators Capsule",
  "Halo Capsule",
  "Half-Life: Alyx Sticker Capsule",
  "Perfect World Sticker Capsule 1",
  "Perfect World Sticker Capsule 2",
  "Poorly Drawn Capsule",
  "Skill Groups Capsule",
  "Warhammer 40,000 Sticker Capsule"
])

function normalizeText(value) {
  return String(value || "").trim()
}

function toSeedRows(items = [], category = "") {
  return items.map((marketHashName) => ({
    marketHashName,
    itemName: marketHashName,
    category,
    tradable: true,
    scanEligible: true,
    isActive: true,
    sourceTag: "manual_primary_seed"
  }))
}

function countByCategory(rows = []) {
  return rows.reduce(
    (counts, row) => {
      const category = normalizeText(row?.category)
      if (!category) return counts
      counts[category] = Number(counts[category] || 0) + 1
      return counts
    },
    {
      weapon_skin: 0,
      case: 0,
      sticker_capsule: 0
    }
  )
}

function validateManualPrimaryCatalogSeed(rows = []) {
  const names = rows.map((row) => normalizeText(row?.marketHashName)).filter(Boolean)
  const uniqueNames = new Set(names.map((name) => name.toLowerCase()))
  if (names.length !== uniqueNames.size) {
    throw new Error("manual_primary_catalog_seed_contains_duplicates")
  }

  const counts = countByCategory(rows)
  if (names.length !== MANUAL_PRIMARY_CATEGORY_COUNTS.total) {
    throw new Error("manual_primary_catalog_seed_total_mismatch")
  }
  if (Number(counts.weapon_skin || 0) !== MANUAL_PRIMARY_CATEGORY_COUNTS.weapon_skin) {
    throw new Error("manual_primary_catalog_seed_weapon_skin_count_mismatch")
  }
  if (Number(counts.case || 0) !== MANUAL_PRIMARY_CATEGORY_COUNTS.case) {
    throw new Error("manual_primary_catalog_seed_case_count_mismatch")
  }
  if (Number(counts.sticker_capsule || 0) !== MANUAL_PRIMARY_CATEGORY_COUNTS.sticker_capsule) {
    throw new Error("manual_primary_catalog_seed_sticker_capsule_count_mismatch")
  }
}

const MANUAL_PRIMARY_CATALOG_SEED = Object.freeze([
  ...toSeedRows(WEAPON_SKIN_ITEMS, "weapon_skin"),
  ...toSeedRows(CASE_ITEMS, "case"),
  ...toSeedRows(STICKER_CAPSULE_ITEMS, "sticker_capsule")
])

validateManualPrimaryCatalogSeed(MANUAL_PRIMARY_CATALOG_SEED)

module.exports = MANUAL_PRIMARY_CATALOG_SEED
module.exports.MANUAL_PRIMARY_CATALOG_SEED = MANUAL_PRIMARY_CATALOG_SEED
module.exports.MANUAL_PRIMARY_CATEGORY_COUNTS = MANUAL_PRIMARY_CATEGORY_COUNTS
