const PLAN_ALIASES = Object.freeze({
  free: "free",
  pro: "full_access",
  team: "full_access",
  full_access: "full_access",
  api_advanced: "full_access",
  alpha_access: "alpha_access",
});

const PLAN_ORDER = Object.freeze({
  free: 0,
  full_access: 1,
  alpha_access: 2,
});

const ACTIVE_PLAN_TIERS = Object.freeze(["free", "full_access"]);
const ALL_PLAN_TIERS = Object.freeze(Object.keys(PLAN_ORDER));

const PLAN_CONFIG = Object.freeze({
  free: Object.freeze({
    plan_tier: "free",
    plan_status: "active",
    roadmap_only: false,
    purchasable: true,
    opportunities_daily_limit: 3,
    alerts_limit: 3,
    minimum_alert_cooldown_minutes: 30,
    scanner_refresh_interval_minutes: 720,
    history_days_limit: 7,
    visible_feed_limit: 10,
    delayed_signals: true,
    signal_delay_minutes: 15,
    advanced_filters: false,
    compare_view: "limited",
    compare_view_max_items: 3,
    portfolio_insights: "basic",
    scanner_categories: Object.freeze(["weapon_skin", "case", "sticker_capsule"]),
    knives_gloves_access: false,
    premium_rare_item_intelligence: false,
    automation: false,
    export_api_ready: false,
    webhooks_ready: false,
    advanced_analytics: false,
    csv_export: false,
    max_csv_rows: 0,
    backtesting: false,
    max_backtest_days: 0,
    team_dashboard: false,
    full_global_scanner: false,
    full_opportunities_feed: false,
    premium_category_access: false,
    scanner_category_access_note: "Knives and gloves are preview-only on Free.",
  }),
  full_access: Object.freeze({
    plan_tier: "full_access",
    plan_status: "active",
    roadmap_only: false,
    purchasable: true,
    opportunities_daily_limit: 500,
    alerts_limit: 25,
    minimum_alert_cooldown_minutes: 0,
    scanner_refresh_interval_minutes: 0,
    history_days_limit: 90,
    visible_feed_limit: 500,
    delayed_signals: false,
    signal_delay_minutes: 0,
    advanced_filters: true,
    compare_view: "full",
    compare_view_max_items: 200,
    portfolio_insights: "full",
    scanner_categories: Object.freeze([
      "weapon_skin",
      "case",
      "sticker_capsule",
      "knife",
      "glove",
    ]),
    knives_gloves_access: true,
    premium_rare_item_intelligence: false,
    automation: false,
    export_api_ready: false,
    webhooks_ready: false,
    advanced_analytics: true,
    csv_export: true,
    max_csv_rows: 100000,
    backtesting: true,
    max_backtest_days: 90,
    team_dashboard: true,
    full_global_scanner: true,
    full_opportunities_feed: true,
    premium_category_access: true,
    scanner_category_access_note:
      "All scanner categories unlocked, including knives and gloves.",
  }),
  alpha_access: Object.freeze({
    plan_tier: "alpha_access",
    plan_status: "coming_soon",
    roadmap_only: true,
    purchasable: false,
    opportunities_daily_limit: 5000,
    alerts_limit: 100,
    minimum_alert_cooldown_minutes: 0,
    scanner_refresh_interval_minutes: 5,
    history_days_limit: 365,
    visible_feed_limit: 5000,
    delayed_signals: false,
    signal_delay_minutes: 0,
    advanced_filters: true,
    compare_view: "advanced",
    compare_view_max_items: 500,
    portfolio_insights: "premium",
    scanner_categories: Object.freeze([
      "weapon_skin",
      "case",
      "sticker_capsule",
      "knife",
      "glove",
    ]),
    knives_gloves_access: true,
    premium_rare_item_intelligence: true,
    automation: true,
    export_api_ready: true,
    webhooks_ready: true,
    advanced_analytics: true,
    csv_export: true,
    max_csv_rows: 250000,
    backtesting: true,
    max_backtest_days: 365,
    team_dashboard: true,
    full_global_scanner: true,
    full_opportunities_feed: true,
    premium_category_access: true,
    scanner_category_access_note:
      "Advanced high-value scanner logic, rare-item intelligence, and automation tooling.",
  }),
});

const TRADER_MODE_ENTITLEMENT_OVERRIDES = Object.freeze({
  alerts_limit: 25,
  history_days_limit: 90,
  max_backtest_days: 90,
  max_csv_rows: 10000,
  advanced_analytics: true,
  csv_export: true,
  backtesting: true,
  portfolio_insights: "full",
});

module.exports = Object.freeze({
  PLAN_CONFIG,
  PLAN_ALIASES,
  PLAN_ORDER,
  ACTIVE_PLAN_TIERS,
  ALL_PLAN_TIERS,
  TRADER_MODE_ENTITLEMENT_OVERRIDES,
});
